"""CLI entry point for forma init — generate forma.yaml configuration template.

Usage::

    forma init [--output PATH] [--force]

Exit codes:
    0 — success
    1 — file exists (no --force)
    2 — write error
"""

from __future__ import annotations

import argparse
import logging
import sys
from pathlib import Path

logger = logging.getLogger(__name__)

# Template with inline comments and sensible defaults
_TEMPLATE = """\
# forma.yaml — Formative assessment analysis project configuration (per semester)
# This file was generated by forma init.
# Per-week settings go in week.yaml.

project:
  course_name: "{course_name}"    # Course name
  year: {year}                     # Academic year (e.g. 2026)
  semester: {semester}             # Semester (1 or 2)
  grade: {grade}                   # Grade level (1 or above)

classes:
  identifiers: {identifiers}      # Class section list (e.g. [A, B, C, D])

paths:
  longitudinal_store: ""           # Longitudinal store YAML path
  font_path: null                  # Font file path (null = auto-detect)

ocr:
  naver_config: ""                 # (deprecated) Naver OCR config — use LLM Vision instead
  ocr_model: null                  # OCR model ID (null = gemini-2.5-flash)
  credentials: ""                  # Credentials (loaded from environment variables)
  spreadsheet_url: ""              # Google Sheets URL

evaluation:
  provider: "gemini"               # LLM provider ("gemini" or "anthropic")
  model: null                      # LLM model name (null = default)
  n_calls: 3                       # Number of LLM calls (1 or above)

reports:
  dpi: 150                         # Chart resolution (72-600)

prediction:
  model_path: null                 # Drop risk prediction model path
"""


def _build_parser() -> argparse.ArgumentParser:
    """Build the argument parser for forma init."""
    parser = argparse.ArgumentParser(
        prog="forma-init",
        description="Generate forma.yaml configuration template",
    )
    parser.add_argument(
        "--output",
        default="forma.yaml",
        help="Output file path (default: ./forma.yaml)",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite existing file",
    )
    return parser


def main() -> None:
    """Entry point for forma init CLI."""
    parser = _build_parser()
    args = parser.parse_args()

    output_path = Path(args.output)

    # Overwrite protection
    if output_path.exists() and not args.force:
        print(
            f"Error: '{output_path}' already exists. Use --force to overwrite.",
            file=sys.stderr,
        )
        sys.exit(1)

    # Interactive prompts
    course_name = input("Course name (course_name, e.g. Anatomy): ").strip()
    year_str = input("Academic year (year, e.g. 2026): ").strip()
    semester_str = input("Semester (semester, 1 or 2): ").strip()
    identifiers_str = input("Class sections (comma-separated, e.g. A,B,C,D): ").strip()

    # Parse inputs with defaults
    year = int(year_str) if year_str.isdigit() else 0
    semester = int(semester_str) if semester_str in ("1", "2") else 0
    grade = 1

    if identifiers_str:
        identifiers = [s.strip() for s in identifiers_str.split(",") if s.strip()]
        identifiers_yaml = "[" + ", ".join(identifiers) + "]"
    else:
        identifiers_yaml = "[]"

    # Generate content
    content = _TEMPLATE.format(
        course_name=course_name,
        year=year,
        semester=semester,
        grade=grade,
        identifiers=identifiers_yaml,
    )

    # Write file
    try:
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(content, encoding="utf-8")
    except OSError as exc:
        print(f"Error: Failed to write '{output_path}': {exc}", file=sys.stderr)
        sys.exit(2)

    print(f"Configuration template generated: {output_path}")


if __name__ == "__main__":
    main()
